# Generated by Django 3.1.2 on 2020-10-23 13:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201014_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to=users.models.user_photos_dir),
        ),
    ]
