# Generated by Django 3.1.2 on 2020-10-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201026_1517'),
        ('users', '0004_user_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_books',
            field=models.ManyToManyField(related_name='read', to='books.Book'),
        ),
    ]
