# Generated by Django 3.1.2 on 2021-01-09 16:55

import books.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=books.models.photos_dir)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_day', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_day', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_day', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='books.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, max_length=500, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=books.models.audio_dir)),
                ('track_name', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('ranges', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='books.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TextOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranges', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('color', models.CharField(max_length=50)),
                ('word', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.text')),
            ],
        ),
    ]
