# Generated by Django 3.1.2 on 2020-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20201115_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoptions',
            name='word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
