# Generated by Django 3.1.2 on 2020-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_textoptions_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
