# Generated by Django 3.1.2 on 2020-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_track_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='track',
            name='uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
