# Generated by Django 3.1.2 on 2020-12-13 07:00

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20201125_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoptions',
            name='types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=books.models.audio_dir),
        ),
    ]
